# CQ07: What are the monitoring requirements?
# Category A: Requirement Retrieval
# Expected: Performance evaluation requirements

PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

SELECT ?definition ?note
WHERE {
  <https://wiren301.github.io/iso27001-skos-taxonomy/27001/clause/9.1> skos:definition ?definition .
  OPTIONAL { <https://wiren301.github.io/iso27001-skos-taxonomy/27001/clause/9.1> skos:note ?note . }
}
