# CQ20: What is a "control"?
# Category D: Vocabulary Understanding
# Expected: ISO 27000 definition of control (term 3.14)

PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

SELECT ?label ?definition
WHERE {
  <https://wiren301.github.io/iso27001-skos-taxonomy/27000/term/3.14> skos:prefLabel ?label ;
                     skos:definition ?definition .
}
